# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: creative_cooking_api_development
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: creative_cooking_api_test
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432


# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
production:
  primary:
    <<: *default
    database: your_app_production
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
    port: <%= ENV['DATABASE_PORT'] || 5432 %>
  cache:
    <<: *default
    database: your_app_production_cache
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
    port: <%= ENV['DATABASE_PORT'] || 5432 %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: your_app_production_queue
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
    port: <%= ENV['DATABASE_PORT'] || 5432 %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: your_app_production_cable
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
    port: <%= ENV['DATABASE_PORT'] || 5432 %>
    migrations_paths: db/cable_migrate
